/* VIEW 1 (Sales Details):
   This view displays detailed information about each sale,
   including customer data, purchased products, quantities,
   individual prices, and the total sale amount.
*/
DROP VIEW IF EXISTS view_verkauf_details;

CREATE VIEW view_verkauf_details AS
SELECT
    verkauf.verkauf_id,
    verkauf.datum,
    kunden.vorname,
    kunden.nachname,
    artikel.bezeichnung AS artikel,
    verkauf_artikel.menge,
    artikel.preis,
    verkauf.gesamtpreis
FROM verkauf
         JOIN kunden ON verkauf.kunden_id = kunden.kunden_id
         JOIN verkauf_artikel ON verkauf.verkauf_id = verkauf_artikel.verkauf_id
         JOIN artikel ON verkauf_artikel.artikel_id = artikel.artikel_id;


/* VIEW 2 (Customer Turnover):
   This view calculates the total revenue generated by each customer
   based on all their purchases.
*/
DROP VIEW IF EXISTS view_customer_turnover;

CREATE VIEW view_customer_turnover AS
SELECT
    kunden.vorname,
    kunden.nachname,
    SUM(verkauf_artikel.menge * artikel.preis) AS gesamtumsatz
FROM kunden
         JOIN verkauf ON kunden.kunden_id = verkauf.kunden_id
         JOIN verkauf_artikel ON verkauf.verkauf_id = verkauf_artikel.verkauf_id
         JOIN artikel ON verkauf_artikel.artikel_id = artikel.artikel_id
GROUP BY kunden.kunden_id, kunden.vorname, kunden.nachname;